openapi: 3.0.3
info:
  title: Phone Number Components
  description: Reusable OpenAPI Components Related to Phone Number Domain Objects
  version: 1.0.0
paths: {}
components:
  schemas:
    PhoneNumber:
      title: Phone Number
      description: String Representation of a Phone Number in e164 Format
      type: string
      pattern: '^\+[1-9]\d{6,14}$'
      example: "+13145551234"

    AreaCode:
      title: Area Code
      description: String Representation of a Three Digit NANP Area Code
      type: string
      pattern: '^[2-9]\d{2}$'
      example: "314"
